package com.example.flighttracker

/**
 * A ship's flag state (country of registration), resolved from the first 3 digits
 * of its MMSI - the Maritime Identification Digits (MID), assigned by the ITU.
 *
 * Note: this is the FLAG STATE, not necessarily the ship's "true" origin. Many
 * cargo/tanker vessels register under flags of convenience (Panama, Liberia,
 * Marshall Islands, Malta) regardless of who owns or crews them.
 */
data class CountryInfo(val name: String, val iso2: String)

/**
 * Free, keyless flag CDN (flagcdn.com). Valid widths: 20, 40, 80, 160, 320, 640.
 * 320 is a reasonable size for a modal background; use something smaller (80/160)
 * for a map badge once that's built.
 */
fun flagUrlFor(country: CountryInfo, widthPx: Int = 320): String =
    "https://flagcdn.com/w$widthPx/${country.iso2.lowercase()}.png"

/**
 * MID -> country, per the ITU's Table of Maritime Identification Digits.
 * Multiple MIDs can map to the same country (large fleets get more than one block).
 */
private val MID_TO_COUNTRY: Map<Int, CountryInfo> = mapOf(
    201 to CountryInfo("Albania", "AL"),
    202 to CountryInfo("Andorra", "AD"),
    203 to CountryInfo("Austria", "AT"),
    204 to CountryInfo("Portugal", "PT"), // Azores
    205 to CountryInfo("Belgium", "BE"),
    206 to CountryInfo("Belarus", "BY"),
    207 to CountryInfo("Bulgaria", "BG"),
    208 to CountryInfo("Vatican City", "VA"),
    209 to CountryInfo("Cyprus", "CY"),
    210 to CountryInfo("Cyprus", "CY"),
    211 to CountryInfo("Germany", "DE"),
    212 to CountryInfo("Cyprus", "CY"),
    213 to CountryInfo("Georgia", "GE"),
    214 to CountryInfo("Moldova", "MD"),
    215 to CountryInfo("Malta", "MT"),
    216 to CountryInfo("Armenia", "AM"),
    218 to CountryInfo("Germany", "DE"),
    219 to CountryInfo("Denmark", "DK"),
    220 to CountryInfo("Denmark", "DK"),
    224 to CountryInfo("Spain", "ES"),
    225 to CountryInfo("Spain", "ES"),
    226 to CountryInfo("France", "FR"),
    227 to CountryInfo("France", "FR"),
    229 to CountryInfo("Malta", "MT"),
    230 to CountryInfo("Finland", "FI"),
    231 to CountryInfo("Faroe Islands", "FO"),
    232 to CountryInfo("United Kingdom", "GB"),
    233 to CountryInfo("United Kingdom", "GB"),
    234 to CountryInfo("United Kingdom", "GB"),
    235 to CountryInfo("United Kingdom", "GB"),
    236 to CountryInfo("Gibraltar", "GI"),
    237 to CountryInfo("Greece", "GR"),
    238 to CountryInfo("Croatia", "HR"),
    239 to CountryInfo("Greece", "GR"),
    240 to CountryInfo("Greece", "GR"),
    241 to CountryInfo("Greece", "GR"),
    242 to CountryInfo("Morocco", "MA"),
    243 to CountryInfo("Hungary", "HU"),
    244 to CountryInfo("Netherlands", "NL"),
    245 to CountryInfo("Netherlands", "NL"),
    246 to CountryInfo("Netherlands", "NL"),
    247 to CountryInfo("Italy", "IT"),
    248 to CountryInfo("Malta", "MT"),
    249 to CountryInfo("Malta", "MT"),
    250 to CountryInfo("Ireland", "IE"),
    251 to CountryInfo("Iceland", "IS"),
    252 to CountryInfo("Liechtenstein", "LI"),
    253 to CountryInfo("Luxembourg", "LU"),
    254 to CountryInfo("Monaco", "MC"),
    255 to CountryInfo("Portugal", "PT"), // Madeira
    256 to CountryInfo("Malta", "MT"),
    257 to CountryInfo("Norway", "NO"),
    258 to CountryInfo("Norway", "NO"),
    259 to CountryInfo("Norway", "NO"),
    261 to CountryInfo("Poland", "PL"),
    262 to CountryInfo("Montenegro", "ME"),
    263 to CountryInfo("Portugal", "PT"),
    264 to CountryInfo("Romania", "RO"),
    265 to CountryInfo("Sweden", "SE"),
    266 to CountryInfo("Sweden", "SE"),
    267 to CountryInfo("Slovakia", "SK"),
    268 to CountryInfo("San Marino", "SM"),
    269 to CountryInfo("Switzerland", "CH"),
    270 to CountryInfo("Czech Republic", "CZ"),
    271 to CountryInfo("Turkey", "TR"),
    272 to CountryInfo("Ukraine", "UA"),
    273 to CountryInfo("Russia", "RU"),
    274 to CountryInfo("North Macedonia", "MK"),
    275 to CountryInfo("Latvia", "LV"),
    276 to CountryInfo("Estonia", "EE"),
    277 to CountryInfo("Lithuania", "LT"),
    278 to CountryInfo("Slovenia", "SI"),
    279 to CountryInfo("Serbia", "RS"),
    301 to CountryInfo("Anguilla", "AI"),
    303 to CountryInfo("United States", "US"), // Alaska
    304 to CountryInfo("Antigua and Barbuda", "AG"),
    305 to CountryInfo("Antigua and Barbuda", "AG"),
    306 to CountryInfo("Curacao", "CW"),
    307 to CountryInfo("Aruba", "AW"),
    308 to CountryInfo("Bahamas", "BS"),
    309 to CountryInfo("Bahamas", "BS"),
    310 to CountryInfo("Bermuda", "BM"),
    311 to CountryInfo("Bahamas", "BS"),
    312 to CountryInfo("Belize", "BZ"),
    314 to CountryInfo("Barbados", "BB"),
    316 to CountryInfo("Canada", "CA"),
    319 to CountryInfo("Cayman Islands", "KY"),
    321 to CountryInfo("Costa Rica", "CR"),
    323 to CountryInfo("Cuba", "CU"),
    325 to CountryInfo("Dominica", "DM"),
    327 to CountryInfo("Dominican Republic", "DO"),
    329 to CountryInfo("Guadeloupe", "GP"),
    330 to CountryInfo("Grenada", "GD"),
    331 to CountryInfo("Greenland", "GL"),
    332 to CountryInfo("Guatemala", "GT"),
    335 to CountryInfo("Honduras", "HN"),
    336 to CountryInfo("Haiti", "HT"),
    338 to CountryInfo("United States", "US"),
    339 to CountryInfo("Jamaica", "JM"),
    341 to CountryInfo("Saint Kitts and Nevis", "KN"),
    343 to CountryInfo("Saint Lucia", "LC"),
    345 to CountryInfo("Mexico", "MX"),
    347 to CountryInfo("Martinique", "MQ"),
    348 to CountryInfo("Montserrat", "MS"),
    350 to CountryInfo("Nicaragua", "NI"),
    351 to CountryInfo("Panama", "PA"),
    352 to CountryInfo("Panama", "PA"),
    353 to CountryInfo("Panama", "PA"),
    354 to CountryInfo("Panama", "PA"),
    358 to CountryInfo("Puerto Rico", "PR"),
    359 to CountryInfo("El Salvador", "SV"),
    361 to CountryInfo("Saint Pierre and Miquelon", "PM"),
    362 to CountryInfo("Trinidad and Tobago", "TT"),
    364 to CountryInfo("Turks and Caicos Islands", "TC"),
    366 to CountryInfo("United States", "US"),
    367 to CountryInfo("United States", "US"),
    368 to CountryInfo("United States", "US"),
    369 to CountryInfo("United States", "US"),
    370 to CountryInfo("Panama", "PA"),
    371 to CountryInfo("Panama", "PA"),
    372 to CountryInfo("Panama", "PA"),
    373 to CountryInfo("Panama", "PA"),
    375 to CountryInfo("Saint Vincent and the Grenadines", "VC"),
    376 to CountryInfo("Saint Vincent and the Grenadines", "VC"),
    377 to CountryInfo("Saint Vincent and the Grenadines", "VC"),
    378 to CountryInfo("British Virgin Islands", "VG"),
    379 to CountryInfo("US Virgin Islands", "VI"),
    401 to CountryInfo("Afghanistan", "AF"),
    403 to CountryInfo("Saudi Arabia", "SA"),
    405 to CountryInfo("Bangladesh", "BD"),
    408 to CountryInfo("Bahrain", "BH"),
    410 to CountryInfo("Bhutan", "BT"),
    412 to CountryInfo("China", "CN"),
    413 to CountryInfo("China", "CN"),
    414 to CountryInfo("China", "CN"),
    416 to CountryInfo("Taiwan", "TW"),
    417 to CountryInfo("Sri Lanka", "LK"),
    419 to CountryInfo("India", "IN"),
    422 to CountryInfo("Iran", "IR"),
    423 to CountryInfo("Azerbaijan", "AZ"),
    425 to CountryInfo("Iraq", "IQ"),
    428 to CountryInfo("Israel", "IL"),
    431 to CountryInfo("Japan", "JP"),
    432 to CountryInfo("Japan", "JP"),
    434 to CountryInfo("Turkmenistan", "TM"),
    436 to CountryInfo("Kazakhstan", "KZ"),
    437 to CountryInfo("Uzbekistan", "UZ"),
    438 to CountryInfo("Jordan", "JO"),
    440 to CountryInfo("South Korea", "KR"),
    441 to CountryInfo("South Korea", "KR"),
    443 to CountryInfo("Palestine", "PS"),
    445 to CountryInfo("North Korea", "KP"),
    447 to CountryInfo("Kuwait", "KW"),
    450 to CountryInfo("Lebanon", "LB"),
    451 to CountryInfo("Kyrgyzstan", "KG"),
    453 to CountryInfo("Macao", "MO"),
    455 to CountryInfo("Maldives", "MV"),
    457 to CountryInfo("Mongolia", "MN"),
    459 to CountryInfo("Nepal", "NP"),
    461 to CountryInfo("Oman", "OM"),
    463 to CountryInfo("Pakistan", "PK"),
    466 to CountryInfo("Qatar", "QA"),
    468 to CountryInfo("Syria", "SY"),
    470 to CountryInfo("United Arab Emirates", "AE"),
    472 to CountryInfo("Tajikistan", "TJ"),
    473 to CountryInfo("Yemen", "YE"),
    475 to CountryInfo("Yemen", "YE"),
    477 to CountryInfo("Hong Kong", "HK"),
    478 to CountryInfo("Bosnia and Herzegovina", "BA"),
    501 to CountryInfo("France", "FR"), // Adelie Land
    503 to CountryInfo("Australia", "AU"),
    506 to CountryInfo("Myanmar", "MM"),
    508 to CountryInfo("Brunei", "BN"),
    510 to CountryInfo("Micronesia", "FM"),
    511 to CountryInfo("Palau", "PW"),
    512 to CountryInfo("New Zealand", "NZ"),
    514 to CountryInfo("Cambodia", "KH"),
    515 to CountryInfo("Cambodia", "KH"),
    516 to CountryInfo("Christmas Island", "CX"),
    518 to CountryInfo("Cook Islands", "CK"),
    520 to CountryInfo("Fiji", "FJ"),
    523 to CountryInfo("Cocos (Keeling) Islands", "CC"),
    525 to CountryInfo("Indonesia", "ID"),
    529 to CountryInfo("Kiribati", "KI"),
    531 to CountryInfo("Laos", "LA"),
    533 to CountryInfo("Malaysia", "MY"),
    536 to CountryInfo("Northern Mariana Islands", "MP"),
    538 to CountryInfo("Marshall Islands", "MH"),
    540 to CountryInfo("New Caledonia", "NC"),
    542 to CountryInfo("Niue", "NU"),
    544 to CountryInfo("Nauru", "NR"),
    546 to CountryInfo("French Polynesia", "PF"),
    548 to CountryInfo("Philippines", "PH"),
    553 to CountryInfo("Papua New Guinea", "PG"),
    555 to CountryInfo("Pitcairn Islands", "PN"),
    557 to CountryInfo("Solomon Islands", "SB"),
    559 to CountryInfo("American Samoa", "AS"),
    561 to CountryInfo("Samoa", "WS"),
    563 to CountryInfo("Singapore", "SG"),
    564 to CountryInfo("Singapore", "SG"),
    565 to CountryInfo("Singapore", "SG"),
    566 to CountryInfo("Singapore", "SG"),
    567 to CountryInfo("Thailand", "TH"),
    570 to CountryInfo("Tonga", "TO"),
    572 to CountryInfo("Tuvalu", "TV"),
    574 to CountryInfo("Vietnam", "VN"),
    576 to CountryInfo("Vanuatu", "VU"),
    577 to CountryInfo("Vanuatu", "VU"),
    578 to CountryInfo("Wallis and Futuna", "WF"),
    601 to CountryInfo("South Africa", "ZA"),
    603 to CountryInfo("Angola", "AO"),
    605 to CountryInfo("Algeria", "DZ"),
    607 to CountryInfo("France", "FR"), // Saint Paul and Amsterdam Islands
    608 to CountryInfo("United Kingdom", "GB"), // Ascension Island
    609 to CountryInfo("Burundi", "BI"),
    610 to CountryInfo("Benin", "BJ"),
    611 to CountryInfo("Botswana", "BW"),
    613 to CountryInfo("Cameroon", "CM"),
    615 to CountryInfo("Congo", "CG"),
    616 to CountryInfo("Comoros", "KM"),
    617 to CountryInfo("Cabo Verde", "CV"),
    618 to CountryInfo("France", "FR"), // Kerguelen/Crozet
    619 to CountryInfo("Ivory Coast", "CI"),
    620 to CountryInfo("Comoros", "KM"),
    621 to CountryInfo("Djibouti", "DJ"),
    622 to CountryInfo("Egypt", "EG"),
    624 to CountryInfo("Ethiopia", "ET"),
    625 to CountryInfo("Eritrea", "ER"),
    626 to CountryInfo("Gabon", "GA"),
    627 to CountryInfo("Ghana", "GH"),
    629 to CountryInfo("Gambia", "GM"),
    630 to CountryInfo("Guinea-Bissau", "GW"),
    631 to CountryInfo("Equatorial Guinea", "GQ"),
    632 to CountryInfo("Guinea", "GN"),
    633 to CountryInfo("Burkina Faso", "BF"),
    634 to CountryInfo("Kenya", "KE"),
    635 to CountryInfo("France", "FR"), // Kerguelen Islands
    636 to CountryInfo("Liberia", "LR"),
    637 to CountryInfo("Liberia", "LR"),
    638 to CountryInfo("South Sudan", "SS"),
    642 to CountryInfo("Libya", "LY"),
    644 to CountryInfo("Lesotho", "LS"),
    645 to CountryInfo("Mauritius", "MU"),
    647 to CountryInfo("Madagascar", "MG"),
    649 to CountryInfo("Mali", "ML"),
    650 to CountryInfo("Mozambique", "MZ"),
    654 to CountryInfo("Mauritania", "MR"),
    655 to CountryInfo("Malawi", "MW"),
    656 to CountryInfo("Nigeria", "NG"),
    659 to CountryInfo("Namibia", "NA"),
    660 to CountryInfo("Reunion", "RE"),
    661 to CountryInfo("Rwanda", "RW"),
    662 to CountryInfo("Sudan", "SD"),
    663 to CountryInfo("Senegal", "SN"),
    664 to CountryInfo("Seychelles", "SC"),
    665 to CountryInfo("Saint Helena", "SH"),
    666 to CountryInfo("Somalia", "SO"),
    667 to CountryInfo("Sierra Leone", "SL"),
    668 to CountryInfo("Sao Tome and Principe", "ST"),
    669 to CountryInfo("Eswatini", "SZ"),
    670 to CountryInfo("Chad", "TD"),
    671 to CountryInfo("Togo", "TG"),
    672 to CountryInfo("Tunisia", "TN"),
    674 to CountryInfo("Tanzania", "TZ"),
    675 to CountryInfo("Uganda", "UG"),
    676 to CountryInfo("DR Congo", "CD"),
    677 to CountryInfo("Tanzania", "TZ"),
    678 to CountryInfo("Zambia", "ZM"),
    679 to CountryInfo("Zimbabwe", "ZW"),
    701 to CountryInfo("Argentina", "AR"),
    710 to CountryInfo("Brazil", "BR"),
    720 to CountryInfo("Bolivia", "BO"),
    725 to CountryInfo("Chile", "CL"),
    730 to CountryInfo("Colombia", "CO"),
    735 to CountryInfo("Ecuador", "EC"),
    740 to CountryInfo("Falkland Islands", "FK"),
    745 to CountryInfo("French Guiana", "GF"),
    750 to CountryInfo("Guyana", "GY"),
    755 to CountryInfo("Paraguay", "PY"),
    760 to CountryInfo("Peru", "PE"),
    765 to CountryInfo("Suriname", "SR"),
    770 to CountryInfo("Uruguay", "UY"),
    775 to CountryInfo("Venezuela", "VE")
)

/**
 * Resolves a ship's flag state from its MMSI. Returns null for MIDs that don't
 * appear in the table (coast stations, aids to navigation, malformed MMSIs, or
 * MIDs the ITU hasn't allocated) - callers should treat that as "unknown," not
 * an error.
 */
fun countryForMmsi(mmsi: Long): CountryInfo? {
    val mid = (mmsi / 1_000_000).toInt()
    return MID_TO_COUNTRY[mid]
}